export type Severity = "info" | "low" | "medium" | "high" | "critical" | string;
export interface EventItem { event_id:string; evidence_file_id?:string|null; external_evidence_id?:string|null; event_origin?:string; timestamp_original:string|null; timestamp_normalized:string|null; timezone:string|null; source_type:string; source_name:string; host:string|null; event_category:string; event_action:string; event_outcome:string|null; severity:Severity; username:string|null; source_ip:string|null; destination_ip:string|null; process_name:string|null; file_name:string|null; raw_log:string; raw_line_number:number|null; parser_name:string; parser_confidence:number; tags:string[]; session_id:string|null; timestamp_confidence:number; timestamp_assumptions:string[]; year_source:string|null; timezone_source:string|null; }
export interface Correlation { correlation_id:string; event_id:string; related_event_id:string; entity_type:string; entity_value:string; correlation_reason:string; time_delta_seconds:number; }
export interface TimelineItem { event:EventItem; correlations:Correlation[]; }
export interface TimelinePage { items:TimelineItem[]; page:number; page_size:number; total:number; }
export interface EventPage { items:EventItem[]; page:number; page_size:number; total:number; }
export interface EventContext { event:EventItem; before:EventItem[]; after:EventItem[]; }
export interface ExternalEvidenceItem { evidence_id:string; provider:string; source_name:string; external_event_id:string; timestamp_original:string|null; timestamp_normalized:string|null; raw_log:string; raw_line_number:number|null; content_sha256:string; retrieved_at:string; source_ip:string|null; username:string|null; host:string|null; event_action:string|null; event_outcome:string|null; severity:Severity; tags:string[]; }
export interface Entity { entity_type:string; entity_value:string; event_count:number; first_seen:string|null; last_seen:string|null; }
export interface EvidenceFile { evidence_file_id:string; case_id:string; original_filename:string; sha256:string; size_bytes:number; detected_format:string|null; status:string; error_message:string|null; uploaded_at:string; parsed_at:string|null; job_id:string|null; parsing_mode:string; total_lines:number; processed_lines:number; parsed_events:number; malformed_lines:number; progress_percent:number; heartbeat_at:string|null; completeness_ratio:number; integrity_status:string|null; integrity_verified_at:string|null; }
export interface Finding { finding_id:string; finding_type:string; title:string; description:string; entity_type:string; entity_value:string; first_seen:string; last_seen:string; evidence_ids:string[]; risk_score:number; risk_breakdown:{formula:string;risk_version?:string;risk_level?:string;components:Record<string,{value:number;weight:number;contribution:number;raw_count?:number;cap?:number}>}; confidence_score:number; confidence_breakdown:{confidence_level?:string;components?:Record<string,number>}; mitre_technique?:string|null; mitre_tactic?:string|null; false_positive_considerations:string[]; recommended_queries:string[]; workflow_status:"new"|"triaging"|"escalated"|"contained"|"closed"; disposition:string|null; assigned_to:string|null; analyst_notes:{author:string;timestamp:string;text:string}[]; workflow_updated_at:string|null; }
export interface Claim { claim_id:string|null; hypothesis_id?:string|null; text:string; status:"fact"|"inference"|"hypothesis"; evidence_id:string; supporting_evidence_ids:string[]; contradicting_evidence_ids:string[]; entities:Record<string,string>; confidence:number|null; reasoning_summary:string|null; limitations:string[]; required_additional_evidence:string[]; verification_status?:"verified"|"repaired"|"rejected"; verification_reasons?:string[]; }
export interface ChatResponse { answer:string; claims:Claim[]; agent_run_id?:string|null; run_status?:string; investigation?:Record<string,unknown>; verification_summary?:Record<string,unknown>; }
export interface AgentRunStep { agent_step_id:string; agent_run_id:string; step_number:number; step_type:string; name:string; status:string; input_data:Record<string,unknown>; output_data:Record<string,unknown>; evidence_ids:string[]; error_code:string|null; started_at:string; ended_at:string|null; latency_ms:number|null; }
export interface AgentRunLedger { ledger_id:string; agent_run_id:string; evidence_id:string; evidence_kind:string; source_tool:string; reference_count:number; details:Record<string,unknown>; first_seen_at:string; last_seen_at:string; }
export interface AgentRunDetail { run:{ agent_run_id:string; case_id:string; state_version:string; status:string; question:string; current_step:number; cancel_requested:boolean; stop_reason:string|null; prompt_version:string|null; model_version:string|null; graph_version:string; state_summary:Record<string,unknown>; created_at:string; updated_at:string; }; investigation?:Record<string,unknown>; steps:AgentRunStep[]; evidence_ledger:AgentRunLedger[]; snapshots?:{ snapshot_id:string; snapshot_type:string; replay_mode:string|null; snapshot_hash:string; source_run_id:string|null; created_at:string }[]; }
